version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_cine
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: api_cine
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - cine_network

volumes:
  mongodb_data:
  mongodb_config:

networks:
  cine_network:
    driver: bridge
