// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/peliculas": {
    params: {};
  };
  "/dashboard/reservas": {
    params: {};
  };
  "/dashboard/reservas/checkout": {
    params: {};
  };
  "/dashboard/usuarios": {
    params: {};
  };
  "/dashboard/salas": {
    params: {};
  };
  "/dashboard/asientos": {
    params: {};
  };
  "/dashboard/funciones": {
    params: {};
  };
  "/dashboard/snacks": {
    params: {};
  };
  "/dashboard/pedidos": {
    params: {};
  };
  "/dashboard/pagos": {
    params: {};
  };
  "/dashboard/configuracion": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/dashboard" | "/dashboard/peliculas" | "/dashboard/reservas" | "/dashboard/reservas/checkout" | "/dashboard/usuarios" | "/dashboard/salas" | "/dashboard/asientos" | "/dashboard/funciones" | "/dashboard/snacks" | "/dashboard/pedidos" | "/dashboard/pagos" | "/dashboard/configuracion";
  };
  "routes/layout.public.tsx": {
    id: "routes/layout.public";
    page: "/" | "/login" | "/register";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/dashboard/layout.tsx": {
    id: "routes/dashboard/layout";
    page: "/dashboard" | "/dashboard/peliculas" | "/dashboard/reservas" | "/dashboard/reservas/checkout" | "/dashboard/usuarios" | "/dashboard/salas" | "/dashboard/asientos" | "/dashboard/funciones" | "/dashboard/snacks" | "/dashboard/pedidos" | "/dashboard/pagos" | "/dashboard/configuracion";
  };
  "routes/dashboard/home.tsx": {
    id: "routes/dashboard/home";
    page: "/dashboard";
  };
  "routes/dashboard/peliculas.tsx": {
    id: "routes/dashboard/peliculas";
    page: "/dashboard/peliculas";
  };
  "routes/dashboard/reservas.tsx": {
    id: "routes/dashboard/reservas";
    page: "/dashboard/reservas";
  };
  "routes/dashboard/order-details.tsx": {
    id: "routes/dashboard/order-details";
    page: "/dashboard/reservas/checkout";
  };
  "routes/dashboard/usuarios.tsx": {
    id: "routes/dashboard/usuarios";
    page: "/dashboard/usuarios";
  };
  "routes/dashboard/salas.tsx": {
    id: "routes/dashboard/salas";
    page: "/dashboard/salas";
  };
  "routes/dashboard/asientos.tsx": {
    id: "routes/dashboard/asientos";
    page: "/dashboard/asientos";
  };
  "routes/dashboard/funciones.tsx": {
    id: "routes/dashboard/funciones";
    page: "/dashboard/funciones";
  };
  "routes/dashboard/snacks.tsx": {
    id: "routes/dashboard/snacks";
    page: "/dashboard/snacks";
  };
  "routes/dashboard/pedidos.tsx": {
    id: "routes/dashboard/pedidos";
    page: "/dashboard/pedidos";
  };
  "routes/dashboard/pagos.tsx": {
    id: "routes/dashboard/pagos";
    page: "/dashboard/pagos";
  };
  "routes/dashboard/configuracion.tsx": {
    id: "routes/dashboard/configuracion";
    page: "/dashboard/configuracion";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout.public": typeof import("./app/routes/layout.public.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/dashboard/layout": typeof import("./app/routes/dashboard/layout.tsx");
  "routes/dashboard/home": typeof import("./app/routes/dashboard/home.tsx");
  "routes/dashboard/peliculas": typeof import("./app/routes/dashboard/peliculas.tsx");
  "routes/dashboard/reservas": typeof import("./app/routes/dashboard/reservas.tsx");
  "routes/dashboard/order-details": typeof import("./app/routes/dashboard/order-details.tsx");
  "routes/dashboard/usuarios": typeof import("./app/routes/dashboard/usuarios.tsx");
  "routes/dashboard/salas": typeof import("./app/routes/dashboard/salas.tsx");
  "routes/dashboard/asientos": typeof import("./app/routes/dashboard/asientos.tsx");
  "routes/dashboard/funciones": typeof import("./app/routes/dashboard/funciones.tsx");
  "routes/dashboard/snacks": typeof import("./app/routes/dashboard/snacks.tsx");
  "routes/dashboard/pedidos": typeof import("./app/routes/dashboard/pedidos.tsx");
  "routes/dashboard/pagos": typeof import("./app/routes/dashboard/pagos.tsx");
  "routes/dashboard/configuracion": typeof import("./app/routes/dashboard/configuracion.tsx");
};