// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/peliculas": {
    params: {};
  };
  "/dashboard/reservas": {
    params: {};
  };
  "/dashboard/configuracion": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/dashboard" | "/dashboard/peliculas" | "/dashboard/reservas" | "/dashboard/configuracion";
  };
  "routes/layout.public.tsx": {
    id: "routes/layout.public";
    page: "/" | "/login" | "/register";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/dashboard/layout.tsx": {
    id: "routes/dashboard/layout";
    page: "/dashboard" | "/dashboard/peliculas" | "/dashboard/reservas" | "/dashboard/configuracion";
  };
  "routes/dashboard/home.tsx": {
    id: "routes/dashboard/home";
    page: "/dashboard";
  };
  "routes/dashboard/peliculas.tsx": {
    id: "routes/dashboard/peliculas";
    page: "/dashboard/peliculas";
  };
  "routes/dashboard/reservas.tsx": {
    id: "routes/dashboard/reservas";
    page: "/dashboard/reservas";
  };
  "routes/dashboard/configuracion.tsx": {
    id: "routes/dashboard/configuracion";
    page: "/dashboard/configuracion";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout.public": typeof import("./app/routes/layout.public.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/dashboard/layout": typeof import("./app/routes/dashboard/layout.tsx");
  "routes/dashboard/home": typeof import("./app/routes/dashboard/home.tsx");
  "routes/dashboard/peliculas": typeof import("./app/routes/dashboard/peliculas.tsx");
  "routes/dashboard/reservas": typeof import("./app/routes/dashboard/reservas.tsx");
  "routes/dashboard/configuracion": typeof import("./app/routes/dashboard/configuracion.tsx");
};